import { RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useQuery } from "@tanstack/react-query";
import type { AccountsResponse, DashboardSummary, UpcomingObligation } from "@worthlane/types";
import { api } from "@/lib/api";
import { spacing, radius } from "@/lib/theme";
import { useThemedStyles, type Theme } from "@/lib/ThemeContext";

const currency = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
function greeting() { const hour = new Date().getHours(); return hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening"; }
function relativeDate(date: string) { const today = new Date(); today.setHours(0, 0, 0, 0); const due = new Date(`${date}T12:00:00`); const days = Math.round((due.getTime() - today.getTime()) / 86_400_000); return days === 0 ? "Today" : days === 1 ? "Tomorrow" : days < 0 ? `${Math.abs(days)} days overdue` : `In ${days} days`; }

function NextRow({ item }: { item: UpcomingObligation }) { const styles = useThemedStyles(createStyles); return <View style={styles.nextRow}><View style={styles.nextMain}><Text style={styles.nextName}>{item.name}</Text><Text style={styles.nextMeta}>{item.type.replace("_", " ")} · {relativeDate(item.dueDate)}</Text></View><View style={styles.nextRight}><Text style={styles.nextAmount}>{currency(item.amount)}</Text><Text style={styles.status}>{item.status === "DUE_TODAY" ? "Due today" : item.status === "OVERDUE" ? "Overdue" : "Upcoming"}</Text></View></View>; }

export default function DashboardScreen() {
  const insets = useSafeAreaInsets(); const styles = useThemedStyles(createStyles);
  const dashboard = useQuery({ queryKey: ["dashboard"], queryFn: () => api.get<DashboardSummary>("/dashboard") });
  const accounts = useQuery({ queryKey: ["accounts"], queryFn: () => api.get<AccountsResponse>("/accounts") });
  const data = dashboard.data?.today;
  const firstRun = !accounts.isLoading && (accounts.data?.accounts.length ?? 0) === 0;
  const refresh = () => { dashboard.refetch(); accounts.refetch(); };
  return <ScrollView style={styles.container} contentContainerStyle={[styles.content, { paddingTop: insets.top + spacing.md }]} refreshControl={<RefreshControl refreshing={dashboard.isRefetching || accounts.isRefetching} onRefresh={refresh} />}>
    <Text style={styles.greeting}>{greeting()}</Text><Text style={styles.date}>{new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric" }).format(new Date())}</Text>
    {dashboard.isLoading ? <Text style={styles.muted}>Loading your snapshot…</Text> : null}
    {dashboard.isError ? <View style={styles.errorCard}><Text style={styles.errorTitle}>Your snapshot is unavailable right now.</Text><Text style={styles.muted}>Your saved information will be here when the connection is back.</Text><TouchableOpacity onPress={() => dashboard.refetch()}><Text style={styles.link}>Try again</Text></TouchableOpacity></View> : null}
    {firstRun ? <View style={styles.firstRun}><Text style={styles.firstTitle}>A calmer view of your money, one detail at a time.</Text><Text style={styles.muted}>Start with anything you know today. You can add the rest later.</Text><TouchableOpacity style={styles.primary} onPress={() => router.push("/accounts")}><Text style={styles.primaryText}>Add your first account</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={() => router.push("/quick-add?kind=bill" as any)}><Text style={styles.secondaryText}>Add an upcoming bill</Text></TouchableOpacity><TouchableOpacity onPress={() => router.push("/quick-add?kind=expense" as any)}><Text style={styles.link}>Add a transaction</Text></TouchableOpacity><Text style={styles.note}>Automatic bank syncing with Plaid is coming soon.</Text></View> : null}
    {data && !firstRun ? <><View style={styles.snapshot}><Text style={styles.snapshotLabel}>Available balance</Text><Text style={styles.balance}>{data.availableBalance === null ? "Add an account to see this" : currency(data.availableBalance)}</Text><View style={styles.metrics}><View><Text style={styles.metricLabel}>Spent this month</Text><Text style={styles.metric}>{currency(data.spentThisMonth)}</Text></View><View><Text style={styles.metricLabel}>Received</Text><Text style={styles.metric}>{currency(data.receivedThisMonth)}</Text></View></View></View><View style={styles.dueCard}><Text style={styles.dueTitle}>{data.upcomingCount ? `${data.upcomingCount} payment${data.upcomingCount === 1 ? "" : "s"} coming up` : "You’re all caught up."}</Text><Text style={styles.muted}>{data.upcomingCount ? `${currency(data.dueNextSevenDays)} is due in the next seven days.` : "Add an upcoming item whenever you’re ready."}</Text></View><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>What’s next</Text><TouchableOpacity onPress={() => router.push("/(tabs)/upcoming" as any)} accessibilityLabel="See all upcoming items"><Text style={styles.link}>See all</Text></TouchableOpacity></View>{data.nextItems.length ? <View style={styles.nextCard}>{data.nextItems.map((item) => <NextRow key={item.id} item={item} />)}</View> : <View style={styles.nextCard}><Text style={styles.muted}>No upcoming items yet.</Text></View>}</> : null}
    <TouchableOpacity style={styles.quickAdd} onPress={() => router.push("/quick-add" as any)} accessibilityLabel="Quick add a financial item"><Text style={styles.quickAddText}>+ Quick add</Text></TouchableOpacity>
  </ScrollView>;
}
const createStyles = ({ colors, typography }: Theme) => StyleSheet.create({ container: { flex: 1, backgroundColor: colors.bg }, content: { padding: spacing.md, paddingBottom: spacing.xxl }, greeting: { ...typography.h2 }, date: { ...typography.bodySmall, marginTop: 2, marginBottom: spacing.lg }, muted: { ...typography.bodySmall, lineHeight: 20 }, snapshot: { backgroundColor: colors.surface, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, padding: spacing.lg, marginBottom: spacing.md }, snapshotLabel: { ...typography.bodySmall }, balance: { ...typography.number, marginTop: spacing.xs, marginBottom: spacing.lg }, metrics: { flexDirection: "row", justifyContent: "space-between" }, metricLabel: { ...typography.caption }, metric: { ...typography.label, marginTop: 3 }, dueCard: { backgroundColor: colors.primaryDim, borderRadius: radius.md, padding: spacing.md, marginBottom: spacing.lg }, dueTitle: { ...typography.label, marginBottom: 3 }, sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: spacing.sm }, sectionTitle: { ...typography.h3 }, link: { color: colors.primary, fontWeight: "700", marginTop: spacing.sm }, nextCard: { backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md }, nextRow: { flexDirection: "row", paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border }, nextMain: { flex: 1 }, nextName: { ...typography.label }, nextMeta: { ...typography.caption, marginTop: 3 }, nextRight: { alignItems: "flex-end" }, nextAmount: { ...typography.label }, status: { ...typography.caption, marginTop: 3 }, quickAdd: { backgroundColor: colors.primary, borderRadius: radius.full, alignItems: "center", padding: spacing.md, marginTop: spacing.xl }, quickAddText: { color: colors.onPrimary, fontSize: 16, fontWeight: "700" }, firstRun: { backgroundColor: colors.surface, padding: spacing.lg, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, gap: spacing.sm }, firstTitle: { ...typography.h3 }, primary: { backgroundColor: colors.primary, borderRadius: radius.md, padding: spacing.md, alignItems: "center", marginTop: spacing.sm }, primaryText: { color: colors.onPrimary, fontWeight: "700" }, secondary: { borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.md, alignItems: "center" }, secondaryText: { color: colors.text, fontWeight: "600" }, note: { ...typography.caption, marginTop: spacing.md }, errorCard: { backgroundColor: colors.surface, borderRadius: radius.md, padding: spacing.lg, borderWidth: 1, borderColor: colors.danger, marginBottom: spacing.md }, errorTitle: { ...typography.label, color: colors.danger, marginBottom: spacing.xs } });
