import { Text, StyleSheet, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { spacing, radius } from "@/lib/theme";
import { useThemedStyles, type Theme } from "@/lib/ThemeContext";
import { captureV1Event } from "@/lib/v1-analytics";

export default function OnboardingWelcome() {
  const styles = useThemedStyles(createStyles);
  const complete = (path: any) => { captureV1Event("onboarding_completed"); router.push(path); };
  return <SafeAreaView style={styles.container} edges={["top", "bottom"]}><View style={styles.inner}><View><Text style={styles.wordmark}>WORTHLANE</Text><Text style={styles.heading}>Know where you stand today.</Text><Text style={styles.heading}>See what’s next.</Text><Text style={styles.subtitle}>Worthlane keeps your money picture calm and clear with fast manual entry.</Text></View><View style={styles.actions}><TouchableOpacity style={styles.primary} onPress={() => complete("/accounts")} accessibilityLabel="Add your first manual account"><Text style={styles.primaryText}>Add your first account</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={() => complete("/quick-add?kind=bill")} accessibilityLabel="Add an upcoming bill"><Text style={styles.secondaryText}>Add an upcoming bill</Text></TouchableOpacity><TouchableOpacity onPress={() => complete("/(tabs)/dashboard")} accessibilityLabel="Continue without adding data"><Text style={styles.skip}>I’ll add details later</Text></TouchableOpacity><Text style={styles.note}>Automatic bank syncing with Plaid is coming soon.</Text></View></View></SafeAreaView>;
}
const createStyles = ({ colors, typography }: Theme) => StyleSheet.create({ container: { flex: 1, backgroundColor: colors.bg }, inner: { flex: 1, justifyContent: "space-between", padding: spacing.xl }, wordmark: { color: colors.primary, fontSize: 14, fontWeight: "700", letterSpacing: 4, marginTop: spacing.md, marginBottom: spacing.lg }, heading: { ...typography.h1, lineHeight: 40 }, subtitle: { ...typography.body, color: colors.textMuted, lineHeight: 24, marginTop: spacing.md }, actions: { gap: spacing.sm }, primary: { padding: spacing.md, alignItems: "center", borderRadius: radius.md, backgroundColor: colors.primary }, primaryText: { color: colors.onPrimary, fontWeight: "700", fontSize: 16 }, secondary: { padding: spacing.md, alignItems: "center", borderRadius: radius.md, borderWidth: 1, borderColor: colors.border }, secondaryText: { color: colors.text, fontWeight: "600" }, skip: { color: colors.primary, fontWeight: "700", textAlign: "center", padding: spacing.md }, note: { ...typography.caption, textAlign: "center", marginTop: spacing.sm } });
