import type { HouseholdSummary } from "@worthlane/contracts";

export const demoHouseholdSummary: HouseholdSummary = {
  household: {
    id: "household-demo-tyler-rachel",
    name: "Tyler & Rachel",
    timezone: "America/Phoenix",
    currency: "USD",
    updatedAt: "2026-07-16T18:42:00.000Z",
  },
  viewerMemberId: "member-tyler",
  members: [
    {
      id: "member-tyler",
      userId: "user-tyler",
      displayName: "Tyler",
      role: "OWNER",
      isCurrentUser: true,
      incomeBasisMinor: 600_000,
    },
    {
      id: "member-rachel",
      userId: "user-rachel",
      displayName: "Rachel",
      role: "MEMBER",
      isCurrentUser: false,
      incomeBasisMinor: 400_000,
    },
  ],
  finances: {
    scope: "VISIBLE_TO_CALLER",
    visibleNetWorthMinor: 8_499_838,
    detailedAccounts: [
      {
        id: "account-tyler-checking",
        name: "Everyday checking",
        institutionName: "Desert Financial",
        type: "CHECKING",
        currentBalanceMinor: 642_018,
        ownerMemberId: "member-tyler",
        ownerName: "Tyler",
        visibility: "PERSONAL",
        isOwner: true,
        updatedAt: "2026-07-16T18:39:00.000Z",
      },
      {
        id: "account-shared-savings",
        name: "Household savings",
        institutionName: "Ally Bank",
        type: "SAVINGS",
        currentBalanceMinor: 2_485_000,
        ownerMemberId: "member-tyler",
        ownerName: "Tyler",
        visibility: "SHARED",
        isOwner: true,
        updatedAt: "2026-07-16T18:37:00.000Z",
      },
      {
        id: "account-tyler-investment",
        name: "Long-term investing",
        institutionName: "Fidelity",
        type: "INVESTMENT",
        currentBalanceMinor: 4_872_500,
        ownerMemberId: "member-tyler",
        ownerName: "Tyler",
        visibility: "PERSONAL",
        isOwner: true,
        updatedAt: "2026-07-16T17:54:00.000Z",
      },
      {
        id: "account-rachel-card",
        name: "Venture X",
        institutionName: "Capital One",
        type: "CREDIT",
        currentBalanceMinor: 124_680,
        ownerMemberId: "member-rachel",
        ownerName: "Rachel",
        visibility: "SHARED",
        isOwner: false,
        updatedAt: "2026-07-16T18:41:00.000Z",
      },
    ],
    summaryOnlyByOwner: [
      {
        ownerMemberId: "member-rachel",
        ownerName: "Rachel",
        assetsMinor: 1_500_000,
        liabilitiesMinor: 875_000,
        netWorthMinor: 625_000,
      },
    ],
  },
  responsibilities: [
    {
      id: "responsibility-housing",
      name: "Home base",
      categoryId: "category-housing",
      categoryName: "Housing",
      mode: "EQUAL",
      monthlyAmountMinor: 245_000,
      allocations: [
        {
          memberId: "member-tyler",
          displayName: "Tyler",
          shareBasisPoints: 5000,
          assignedMinor: 122_500,
          appliedSpendMinor: 122_500,
          remainingMinor: 0,
          percentUsed: 100,
        },
        {
          memberId: "member-rachel",
          displayName: "Rachel",
          shareBasisPoints: 5000,
          assignedMinor: 122_500,
          appliedSpendMinor: 122_500,
          remainingMinor: 0,
          percentUsed: 100,
        },
      ],
      updatedAt: "2026-07-01T15:00:00.000Z",
    },
    {
      id: "responsibility-groceries",
      name: "Groceries",
      categoryId: "category-groceries",
      categoryName: "Groceries",
      mode: "PERCENTAGE",
      monthlyAmountMinor: 72_000,
      allocations: [
        {
          memberId: "member-tyler",
          displayName: "Tyler",
          shareBasisPoints: 6000,
          assignedMinor: 43_200,
          appliedSpendMinor: 28_644,
          remainingMinor: 14_556,
          percentUsed: 66.31,
        },
        {
          memberId: "member-rachel",
          displayName: "Rachel",
          shareBasisPoints: 4000,
          assignedMinor: 28_800,
          appliedSpendMinor: 19_096,
          remainingMinor: 9_704,
          percentUsed: 66.31,
        },
      ],
      updatedAt: "2026-07-15T23:08:00.000Z",
    },
    {
      id: "responsibility-utilities",
      name: "Utilities",
      categoryId: "category-utilities",
      categoryName: "Utilities",
      mode: "MEMBER",
      monthlyAmountMinor: 36_000,
      allocations: [
        {
          memberId: "member-rachel",
          displayName: "Rachel",
          shareBasisPoints: 10_000,
          assignedMinor: 36_000,
          appliedSpendMinor: 28_645,
          remainingMinor: 7_355,
          percentUsed: 79.57,
        },
      ],
      updatedAt: "2026-07-14T19:22:00.000Z",
    },
    {
      id: "responsibility-dining",
      name: "Dining out",
      categoryId: "category-dining",
      categoryName: "Dining",
      mode: "MEMBER",
      monthlyAmountMinor: 30_000,
      allocations: [
        {
          memberId: "member-tyler",
          displayName: "Tyler",
          shareBasisPoints: 10_000,
          assignedMinor: 30_000,
          appliedSpendMinor: 18_412,
          remainingMinor: 11_588,
          percentUsed: 61.37,
        },
      ],
      updatedAt: "2026-07-16T18:02:00.000Z",
    },
  ],
  sharedGoals: [
    {
      id: "goal-universal-orlando",
      name: "Universal Orlando",
      targetAmountMinor: 700_000,
      currentAmountMinor: 321_500,
      remainingMinor: 378_500,
      percentComplete: 45.93,
      targetDate: "2027-03-15T12:00:00.000Z",
      icon: "spark",
      contributionMode: "CUSTOM",
      participants: [
        {
          memberId: "member-tyler",
          displayName: "Tyler",
          plannedContributionMinor: 350_000,
          contributedAmountMinor: 165_000,
          remainingMinor: 185_000,
          percentComplete: 47.14,
        },
        {
          memberId: "member-rachel",
          displayName: "Rachel",
          plannedContributionMinor: 350_000,
          contributedAmountMinor: 156_500,
          remainingMinor: 193_500,
          percentComplete: 44.71,
        },
      ],
      recentContributions: [
        {
          id: "contribution-rachel-july",
          memberId: "member-rachel",
          contributorName: "Rachel",
          amountMinor: 12_500,
          note: "July trip fund",
          createdAt: "2026-07-15T17:20:00.000Z",
        },
        {
          id: "contribution-tyler-july",
          memberId: "member-tyler",
          contributorName: "Tyler",
          amountMinor: 15_000,
          note: "A little closer",
          createdAt: "2026-07-12T16:45:00.000Z",
        },
      ],
      updatedAt: "2026-07-15T17:20:00.000Z",
    },
  ],
};
