import type { Metadata } from "next";
import { LegalHeader, SiteFooter } from "@/components/site-chrome";

export const metadata: Metadata = { title: "Privacy", alternates: { canonical: "/privacy" }, description: "How Worthlane handles account, financial, and device data." };
const CONTACT_EMAIL = "support@worthlane.app";

export default function PrivacyPage() {
  return <><LegalHeader /><main id="main" className="legal-page"><article className="site-container legal-copy"><p className="eyebrow">Worthlane policies</p><h1>Privacy, plainly put.</h1><p>Updated September 10, 2026. Worthlane’s couples beta is in development. This page describes the app’s current data flows and the website.</p><section><h2>Information we use</h2><p>When you create an account, Worthlane stores your email address and a securely hashed password. The app also stores the accounts, transactions, categories, budgets, goals, streaks, and preferences you add so it can show your financial picture.</p><p>If you enable push notifications, Worthlane stores a device push token so it can send budget alerts, streak reminders, and other app notifications you have chosen to receive.</p></section><section><h2>How it is used</h2><ul><li>To authenticate you and operate the app.</li><li>To calculate budgets, goals, net worth, and financial insights.</li><li>To provide the in-app financial assistant with the context needed to answer your questions.</li><li>To send opted-in notifications and respond to support requests.</li></ul></section><section><h2>Bank linking</h2><p>The beta uses Plaid Sandbox to test bank connections with test data. Live bank access is not offered through this website. Plaid handles the bank connection flow; Worthlane stores encrypted access tokens and imported account and transaction data for connected beta accounts.</p></section><section><h2>Household sharing</h2><p>Each person has a separate login. Joining a household requires accepting an invitation. Account owners choose personal visibility, balance summaries, or shared detail. Household totals depend on what each login is permitted to see. You can change sharing choices in the app.</p></section><section><h2>Website and app diagnostics</h2><p>This website uses Vercel Analytics and Speed Insights for usage and performance measurements. The beta app has analytics controls; reviewed server events exclude financial amounts, email addresses, and bank identifiers. Support messages include the information you choose to email us. Please do not send passwords or bank credentials.</p></section><section><h2>Keeping control</h2><p>You can remove linked account data from your profile and delete your Worthlane account inside the app. Account deletion permanently removes your account and associated financial data from our systems, subject to any retention required by law.</p></section><section><h2>Contact</h2><p>For privacy questions or requests, contact <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</p></section><aside className="legal-callout"><strong>Your sharing choice matters.</strong> A household invitation does not automatically give your partner access to your account details.</aside></article></main><SiteFooter /></>;
}
