"use client";
import { useState } from "react";
import Link from "next/link";
import { BrandMark } from "./brand";
import { LegalHeader, SiteFooter } from "./site-chrome";

const money = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
const questions = [
  ["Do we need to combine our bank accounts?", "No. Worthlane is being built around separate logins and account ownership. You can plan together while choosing which account details or summaries to share."],
  ["Can I use it on my own?", "Yes. Start with a solo plan. Couples and families can use a household with up to two separate adult logins; joining requires an invitation and acceptance."],
  ["Does Worthlane move our money?", "No. A budget split describes responsibility. It does not transfer money, pay a bill, or create a reimbursement."],
  ["Can I connect my bank?", "Plaid bank connections are being tested in Sandbox for the beta. Live bank access is not available through this website. Manual accounts and transactions are part of the beta too."],
  ["Can I download the beta now?", "The couples beta is still in development. This site shows the planned experience, not an invitation to connect real financial accounts. Contact us with beta questions; access and pricing will be explained before you join."],
];

function SplitExample() {
  const [mode, setMode] = useState("equal");
  const tyler = mode === "equal" ? 50 : mode === "custom" ? 60 : 100;
  const rentTyler = 1700 * tyler / 100;
  return <div className="plan-demo"><div className="demo-top"><span className="eyebrow">An everyday agreement</span><span className="sample-tag">Interactive example</span></div><h3>A place to call ours.</h3><p>Same $1,700 rent. A split that works for you.</p><fieldset className="split-options"><legend className="sr-only">Choose rent responsibility</legend>{[["equal", "50 / 50"], ["custom", "60 / 40"], ["one", "One person"]].map(([value, label]) => <label key={value} className={mode === value ? "selected" : ""}><input type="radio" name="split" value={value} checked={mode === value} onChange={() => setMode(value)} />{label}</label>)}</fieldset><div className="split-result" aria-live="polite" aria-atomic="true"><div><span className="avatar avatar--clay">T</span><span>Tyler <small>{tyler}% responsibility</small></span><strong>{money(rentTyler)}</strong></div><div><span className="avatar">R</span><span>Rachel <small>{100 - tyler}% responsibility</small></span><strong>{money(1700 - rentTyler)}</strong></div><div className="split-bar" aria-hidden="true"><span style={{ width: `${tyler}%` }} /></div><p className="total-row"><span>Household total</span><strong>$1,700</strong></p></div><p className="demo-note">Who paid is a separate detail. Changing responsibility never doubles the household total.</p></div>;
}

export default function Home() {
  return <><LegalHeader /><main id="main">
    <section className="hero"><div className="site-container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> For your next chapter</p><h1>A life together.{" "}<br />A little more{" "}<br /><em>money clarity.</em></h1><p className="lede">Moving in is a big step. Make the money part feel smaller—with a shared plan, clear responsibilities, and space for what’s yours.</p><div className="hero-actions"><a className="button" href="#your-plan">Find your balance <span aria-hidden="true">↗</span></a><a className="text-link" href="#how-it-works">Meet Worthlane <span aria-hidden="true">↓</span></a></div><p className="fine-print">Couples-first beta in development · Solo-friendly, too</p></div><div className="hero-art"><div className="art-orbit" aria-hidden="true"/><div className="household-preview"><div className="preview-heading"><BrandMark /><span>Your shared chapter<small>Tyler & Rachel · September</small></span><span className="tiny-dot" /></div><p className="eyebrow">The plan you agreed on</p><div className="preview-total">$2,450<span>monthly responsibilities</span></div><div className="preview-people"><div><span className="avatar avatar--clay">T</span><span>Tyler<strong>$1,470</strong></span></div><div><span className="avatar">R</span><span>Rachel<strong>$980</strong></span></div></div><div className="preview-row"><span>⌂ <b>Our place</b></span><span>$1,700 <small>60 / 40</small></span></div><div className="preview-row"><span>◌ <b>Groceries</b></span><span>$600 <small>50 / 50</small></span></div><div className="preview-row"><span>☼ <b>Utilities</b></span><span>$150 <small>Tyler</small></span></div><p className="preview-foot">One plan. Two independent logins.</p></div><div className="floating-note"><span aria-hidden="true">✓</span><div>Yours stays yours.<small>You choose what to share.</small></div></div><p className="art-caption">Illustrative plan · no real account data</p></div></div></section>
    <div className="principles"><div className="site-container"><span>Shared plans</span><span>Separate logins</span><span>Clear responsibilities</span><span>Privacy by choice</span></div></div>
    <section id="how-it-works" className="section"><div className="site-container"><div className="section-heading"><p className="eyebrow">Less guessing. More living.</p><h2>Make the small agreements{" "}<br />that make a big difference.</h2><p>Start with one honest conversation. Give the decisions you make a place to live.</p></div><div className="steps"><article><span className="step-number">01 / Start with you</span><h3>Bring your own picture.</h3><p>Add the accounts and spending you want to understand. Begin manually, with bank linking being prepared for beta.</p><div className="mini-visual"><span className="mini-pill">Personal</span><div className="mini-line"/><div className="mini-line short"/></div></article><article><span className="step-number">02 / Make room for two</span><h3>Invite. Don’t assume.</h3><p>Your partner joins with their own login and accepts the invitation. Each person decides what to share.</p><div className="mini-visual people-visual"><span className="avatar avatar--clay">T</span><span className="connecting-line"/><span className="avatar">R</span><span className="mini-pill">Both say yes</span></div></article><article><span className="step-number">03 / Agree on a plan</span><h3>Fair is what you agree.</h3><p>Assign a category to one partner, split it evenly, or choose your percentages. Keep the household total clear.</p><div className="mini-visual"><div className="mini-split"><i/><i/></div><div className="mini-labels"><span>60% yours</span><span>40% theirs</span></div></div></article></div></div></section>
    <section id="your-plan" className="section split-section"><div className="site-container two-column"><div className="section-heading"><p className="eyebrow">A plan that fits real life</p><h2>Equal isn’t the{" "}<br />only kind of <em>fair.</em></h2><p>One of you covers utilities. Groceries are shared. Rent follows the percentages you agree on. Worthlane makes those choices visible.</p><p className="side-note">Try the example. Every split keeps the same household total.</p></div><SplitExample /></div></section>
    <section className="section"><div className="site-container"><div className="section-heading"><p className="eyebrow">Room for today. A view of tomorrow.</p><h2>More of the picture.{" "}<br />Less to keep in your head.</h2></div><div className="feature-grid"><article className="feature-card feature-card--wide"><div><span className="feature-icon" aria-hidden="true">↗</span><h3>Know what’s coming.</h3><p>Keep bill and card due dates in view. Choose reminders, review dates, and mark bills paid. Predicted recurring charges stay distinct from confirmed due dates.</p></div><div className="bill-example"><p><span>UPCOMING</span><small>Example</small></p><div><span className="calendar-date">SEP<strong>20</strong></span><span>Internet<small>Monthly · manual due date</small></span><strong>$85</strong></div></div></article><article className="feature-card"><span className="feature-icon" aria-hidden="true">◎</span><h3>A payoff plan you can follow.</h3><p>Compare debt strategies with visible balances, rates, and assumptions. Save an estimate you can return to as life changes.</p><p className="card-caption">An explanation, not a promise.</p></article></div></div></section>
    <section id="privacy" className="privacy-section"><div className="site-container two-column"><div><p className="eyebrow">Together doesn’t mean everything</p><h2>A shared life.{" "}<br /><em>Personal boundaries.</em></h2><p>You shouldn’t have to surrender your privacy to make a household plan.</p><Link className="text-link" href="/privacy">Read about privacy <span aria-hidden="true">↗</span></Link></div><div className="privacy-choices"><article><span>01</span><div><h3>Personal</h3><p>Keep an account’s details visible to you.</p></div></article><article><span>02</span><div><h3>Summary only</h3><p>Share a balance without the transaction history.</p></div></article><article><span>03</span><div><h3>Shared detail</h3><p>Choose the accounts you both need to understand.</p></div></article></div></div></section>
    <section className="section"><div className="site-container faq-grid"><div className="section-heading"><p className="eyebrow">Good questions</p><h2>Before your{" "}<br />next chapter.</h2><p>Something else on your mind?{" "}<br /><Link href="/support" className="text-link">We’re here to help ↗</Link></p></div><div className="faq-list">{questions.map(([q,a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>
    <section id="beta" className="beta-section"><div className="site-container"><p className="eyebrow">A thoughtful beginning</p><h2>Good with money.{" "}<br /><em>Better, together.</em></h2><p>We’re building and testing the couples beta now. Follow along or ask about joining—we’ll explain availability before you share financial information.</p><a className="button" href="mailto:support@worthlane.app?subject=Worthlane%20beta">Ask about the beta <span aria-hidden="true">↗</span></a><p className="fine-print">Opens your email app. No bank details needed.</p></div></section>
  </main><SiteFooter /></>;
}
