#!/usr/bin/env python3
"""Rehearse a local synthetic backup. Never reads DATABASE_URL or production data."""
import hashlib
import json
import os
from pathlib import Path
import subprocess
import uuid

ROOT = Path(__file__).resolve().parents[1]
BIN = Path(os.environ.get('WORTHLANE_POSTGRES_BIN', '/Applications/Postgres.app/Contents/Versions/17/bin'))
PORT = int(os.environ.get('WORTHLANE_TEST_PORT', '55439'))
if not 1024 < PORT < 65536:
    raise SystemExit('Invalid local test port')
SOURCE = 'worthlane_beta_test'
TARGET = 'worthlane_restore_test_' + uuid.uuid4().hex[:16]
ARTIFACT = ROOT / '.tmp' / TARGET
ARTIFACT.mkdir(parents=True, mode=0o700)
os.umask(0o077)
CONNECTION = ['-h', '127.0.0.1', '-p', str(PORT), '-U', 'worthlane_test']

def run(program, *args):
    result = subprocess.run([str(BIN / program), *args], capture_output=True, text=True)
    if result.returncode:
        # Keep diagnostic output private; never echo possible database records.
        (ARTIFACT / 'error.log').write_text(result.stderr)
        raise RuntimeError(f'{program} failed; private diagnostic: {ARTIFACT / "error.log"}')
    return result.stdout.strip()

def sql(database, statement):
    return run('psql', *CONNECTION, '-d', database, '-X', '-A', '-t', '-v', 'ON_ERROR_STOP=1', '-c', statement)

def fingerprints(database):
    tables = sql(database, "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY tablename").splitlines()
    result = {}
    for table in tables:
        quoted = '"' + table.replace('"', '""') + '"'
        value = sql(database, f"SELECT count(*)::text || '|' || md5(COALESCE(string_agg(md5(to_jsonb(t)::text), '' ORDER BY md5(to_jsonb(t)::text)), '')) FROM public.{quoted} t")
        count, digest = value.split('|')
        result[table] = {'rows': int(count), 'digest': digest}
    return result

created = False
try:
    version = sql(SOURCE, 'SHOW server_version')
    before = fingerprints(SOURCE)
    if not before or before.get('User', {}).get('rows', 0) == 0:
        raise RuntimeError('Seeded synthetic source required; refusing an empty rehearsal')
    dump = ARTIFACT / 'sandbox.dump'
    run('pg_dump', *CONNECTION, '-d', SOURCE, '--format=custom', '--no-owner', '--no-acl', '-f', str(dump))
    after = fingerprints(SOURCE)
    if before != after:
        raise RuntimeError('Synthetic source changed during backup; retry when it is idle')
    run('createdb', *CONNECTION, TARGET)
    created = True
    run('pg_restore', *CONNECTION, '-d', TARGET, '--single-transaction', '--exit-on-error', '--no-owner', '--no-acl', str(dump))
    restored = fingerprints(TARGET)
    if restored != before:
        raise RuntimeError('Restored row counts/content differ from source')
    invalid = sql(TARGET, "SELECT count(*) FROM pg_constraint WHERE connamespace='public'::regnamespace AND NOT convalidated")
    if invalid != '0':
        raise RuntimeError('Restored database contains unvalidated constraints')
    report = {'scope': 'local synthetic database only', 'serverVersion': version,
              'dumpSha256': hashlib.sha256(dump.read_bytes()).hexdigest(),
              'tablesVerified': len(restored), 'rowsVerified': sum(t['rows'] for t in restored.values()),
              'unvalidatedConstraints': 0, 'fingerprints': restored}
    (ARTIFACT / 'report.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps({k: v for k, v in report.items() if k != 'fingerprints'}, indent=2))
    print(f'Private evidence: {ARTIFACT / "report.json"}')
finally:
    if created:
        # TARGET is generated by this run; SOURCE is never a cleanup target.
        run('dropdb', *CONNECTION, TARGET)
