import type { Metadata } from "next";
import { LegalHeader, SiteFooter } from "@/components/site-chrome";

export const metadata: Metadata = { title: "Terms", alternates: { canonical: "/terms" }, description: "Terms for the Worthlane mobile application and website." };
const CONTACT_EMAIL = "support@worthlane.app";

export default function TermsPage() {
  return <><LegalHeader /><main id="main" className="legal-page"><article className="site-container legal-copy"><p className="eyebrow">Worthlane policies</p><h1>Terms of use.</h1><p>Effective July 10, 2026. These terms govern your use of the Worthlane mobile application and website.</p><section><h2>Using Worthlane</h2><p>Worthlane helps you organize financial information you provide, set budgets and goals, and understand your personal money picture. You are responsible for the information you enter and for keeping your account credentials secure.</p></section><section><h2>Not financial advice</h2><p>Worthlane and its in-app assistant provide general, personalized educational context based on the information in your account. They do not provide investment, legal, tax, or other professional advice, and they cannot move money or make transactions for you.</p></section><section><h2>Your account</h2><p>You may delete your account from the app. We may update or discontinue features as we prepare and improve the service; material changes to these terms will be reflected by an updated effective date.</p></section><section><h2>Questions</h2><p>Contact <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> with questions about these terms.</p></section><aside className="legal-callout"><strong>A planning tool.</strong> Estimates depend on the balances, rates, dates, and assumptions supplied. Confirm payment amounts and due dates with your lender or provider.</aside></article></main><SiteFooter /></>;
}
